version: "3.3"
services:
  grafana:
    image: grafana/grafana:latest
    #user: "1000"
    container_name: grafana
    environment:
    #- GF_INSTALL_PLUGINS=http://plugin-domain.com/my-custom-plugin.zip;custom-plugin,grafana-clock-panel
      - PUID=1000
      - PGID=1000
    ports:
      - 3005:3000
    volumes:
      - /var/lib/docker/root_dir/grafana/config:/var/lib/grafana
    networks:
      - grafana  
    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /var/lib/docker/root_dir/grafana/prometheus-etc:/etc/prometheus 
      - /var/lib/docker/root_dir/grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - grafana  
    restart: unless-stopped
    
#  loki: 
#    image: grafana/loki:latest
#    container_name: loki
#    ports:
#      - 3100:3100
#    volumes:
#      - /var/lib/docker/root_dir/grafana/loki-config.yaml:/etc/loki/local-config.yaml
#    networks:
#      - grafana  
#    restart: unless-stopped
    
  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/root_dir/grafana/promtail-etc:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - grafana

  nodered: 
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports: 
      - 1880:1880
    volumes:
      - noderedData:/data
    networks:
      - grafana

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    environment:
      INFLUXDB_DB: DBONE
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: abcd1234
      INFLUXDB_USER: influx
      INFLUXDB_USER_PASSWORD: abcd1234
    ports:
      - 8082:8082
      - 8086:8086
      - 8089:8089
    volumes:
      - influxData:/var/lib/influxdb
    networks: 
      - grafana
      
networks:
  grafana:
volumes:
  noderedData:
  influxData:
